var achievements = [
{ 'name' : 'openInventory', 'label' : 'Taking Inventory' },
{ 'name' : 'mineWood', 'label' : 'Getting Wood' },
{ 'name' : 'buildWorkBench', 'label' : 'Benchmarking' },
{ 'name' : 'buildPickaxe', 'label' : 'Time to Mine!' },
{ 'name' : 'buildFurnace', 'label' : 'Hot Topic' },
{ 'name' : 'acquireIron', 'label' : 'Acquire Hardware' },
{ 'name' : 'buildHoe', 'label' : 'Time to Farm!' },
{ 'name' : 'makeBread', 'label' : 'Bake Bread' },
{ 'name' : 'bakeCake', 'label' : 'The Lie' },
{ 'name' : 'buildBetterPickaxe', 'label' : 'Getting an Upgrade' },
{ 'name' : 'cookFish', 'label' : 'Delicious Fish' },
{ 'name' : 'onARail', 'label' : 'On A Rail' },
{ 'name' : 'buildSword', 'label' : 'Time to Strike!' },
{ 'name' : 'killEnemy', 'label' : 'Monster Hunter' },
{ 'name' : 'killCow', 'label' : 'Cow Tipper' },
{ 'name' : 'flyPig', 'label' : 'When Pigs Fly' },
{ 'name' : 'snipeSkeleton', 'label' : 'Sniper Duel' },
{ 'name' : 'diamonds', 'label' : 'DIAMONDS!' },
{ 'name' : 'portal', 'label' : 'We Need to Go Deeper' },
{ 'name' : 'ghast', 'label' : 'Return to Sender' },
{ 'name' : 'blazeRod', 'label' : 'Into Fire' },
{ 'name' : 'potion', 'label' : 'Local Brewery' },
{ 'name' : 'theEnd', 'label' : 'The End?' },
{ 'name' : 'theEnd2', 'label' : 'The End.' },
{ 'name' : 'enchantments', 'label' : 'Enchanter' },
{ 'name' : 'overkill', 'label' : 'Overkill' },
{ 'name' : 'bookcase', 'label' : 'Librarian' },
{ 'name' : 'exploreAllBiomes', 'label' : 'Adventuring Time' },
{ 'name' : 'spawnWither', 'label' : 'The Beginning?' },
{ 'name' : 'killWither', 'label' : 'The Beginning.' },
{ 'name' : 'fullBeacon', 'label' : 'Beaconator' },
{ 'name' : 'breedCow', 'label' : 'Repopulation' },
{ 'name' : 'diamondsToYou', 'label' : 'Diamonds to you!' }
];

