var blocksByID = new Array();

var blockIDs = [{"id":"0", "name":"Air"},
{"id":"1", "name":"Stone"},
{"id":"2", "name":"Grass"},
{"id":"3", "name":"Dirt"},
{"id":"4", "name":"Cobblestone"},
{"id":"5", "name":"Oak Wood Plank"},
{"id":"5:1", "name":"Spruce Wood Plank"},
{"id":"5:2", "name":"Birch Wood Plank"},
{"id":"5:3", "name":"Jungle Wood Plank"},
{"id":"6", "name":"Oak Sapling"},
{"id":"6:1", "name":"Spruce Sapling"},
{"id":"6:2", "name":"Birch Sapling"},
{"id":"6:3", "name":"Jungle Sapling"},
{"id":"7", "name":"Bedrock"},
{"id":"8", "name":"Water"},
{"id":"9", "name":"Stationary Water"},
{"id":"10", "name":"Lava"},
{"id":"11", "name":"Stationary Lava"},
{"id":"12", "name":"Sand"},
{"id":"13", "name":"Gravel"},
{"id":"14", "name":"Gold Ore"},
{"id":"15", "name":"Iron Ore"},
{"id":"16", "name":"Coal Ore"},
{"id":"17", "name":"Oak Wood"},
{"id":"17:1", "name":"Spruce Wood"},
{"id":"17:2", "name":"Birch Wood"},
{"id":"17:3", "name":"Jungle Wood"},
{"id":"18", "name":"Oak Leaves"},
{"id":"18:1", "name":"Spruce Leaves"},
{"id":"18:2", "name":"Birch Leaves"},
{"id":"18:3", "name":"Jungle Leaves"},
{"id":"19", "name":"Sponge"},
{"id":"20", "name":"Glass"},
{"id":"21", "name":"Lapis Lazuli Ore"},
{"id":"22", "name":"Lapis Lazuli Block"},
{"id":"23", "name":"Dispenser"},
{"id":"24", "name":"Sandstone"},
{"id":"24:1", "name":"Chiseled Sandstone"},
{"id":"24:2", "name":"Smooth Sandstone"},
{"id":"25", "name":"Note Block"},
{"id":"26", "name":"Bed Block"},
{"id":"27", "name":"Powered Rail"},
{"id":"28", "name":"Detector Rail"},
{"id":"29", "name":"Sticky Piston"},
{"id":"30", "name":"Web"},
{"id":"31", "name":"Dead Shrub"},
{"id":"31:1", "name":"Grass"},
{"id":"31:2", "name":"Fern"},
{"id":"32", "name":"Dead Shrub"},
{"id":"33", "name":"Piston"},
{"id":"34", "name":"Piston Head"},
{"id":"35", "name":"White Wool"},
{"id":"35:1", "name":"Orange Wool"},
{"id":"35:2", "name":"Magenta Wool"},
{"id":"35:3", "name":"Light Blue Wool"},
{"id":"35:4", "name":"Yellow Wool"},
{"id":"35:5", "name":"Light Green Wool"},
{"id":"35:6", "name":"Pink Wool"},
{"id":"35:7", "name":"Gray Wool"},
{"id":"35:8", "name":"Light Gray Wool"},
{"id":"35:9", "name":"Cyan Wool"},
{"id":"35:10", "name":"Purple Wool"},
{"id":"35:11", "name":"Blue Wool"},
{"id":"35:12", "name":"Brown Wool"},
{"id":"35:13", "name":"Dark Green Wool"},
{"id":"35:14", "name":"Red Wool"},
{"id":"35:15", "name":"Black Wool"},
{"id":"37", "name":"Dandelion"},
{"id":"38", "name":"Rose"},
{"id":"39", "name":"Brown Mushroom"},
{"id":"40", "name":"Red Mushroom"},
{"id":"41", "name":"Gold Block"},
{"id":"42", "name":"Iron Block"},
{"id":"43", "name":"Double Stone Slab"},
{"id":"43:1", "name":"Double Sandstone Slab"},
{"id":"43:2", "name":"Double Wooden Slab"},
{"id":"43:3", "name":"Double Cobblestone Slab"},
{"id":"43:4", "name":"Double Brick Slab"},
{"id":"43:5", "name":"Double Stone Brick Slab"},
{"id":"43:6", "name":"Double Nether Brick Slab"},
{"id":"43:7", "name":"Double Quartz Slab"},
{"id":"44", "name":"Stone Slab"},
{"id":"44:1", "name":"Sandstone Slab"},
{"id":"44:2", "name":"Wooden Slab"},
{"id":"44:3", "name":"Cobblestone Slab"},
{"id":"44:4", "name":"Brick Slab"},
{"id":"44:5", "name":"Stone Brick Slab"},
{"id":"44:6", "name":"Nether Brick Slab"},
{"id":"44:7", "name":"Quartz Slab"},
{"id":"45", "name":"Brick"},
{"id":"46", "name":"TNT"},
{"id":"47", "name":"Bookshelf"},
{"id":"48", "name":"Mossy Cobblestone"},
{"id":"49", "name":"Obsidian"},
{"id":"50", "name":"Torch"},
{"id":"51", "name":"Fire"},
{"id":"52", "name":"Monster Spawner"},
{"id":"53", "name":"Oak Wood Stairs"},
{"id":"54", "name":"Chest"},
{"id":"55", "name":"Redstone Wire"},
{"id":"56", "name":"Diamond Ore"},
{"id":"57", "name":"Diamond Block"},
{"id":"58", "name":"Workbench"},
{"id":"59", "name":"Wheat Crops"},
{"id":"60", "name":"Soil"},
{"id":"61", "name":"Furnace"},
{"id":"62", "name":"Burning Furnace"},
{"id":"63", "name":"Sign Post"},
{"id":"64", "name":"Wooden Door Block"},
{"id":"65", "name":"Ladder"},
{"id":"66", "name":"Rails"},
{"id":"67", "name":"Cobblestone Stairs"},
{"id":"68", "name":"Wall Sign"},
{"id":"69", "name":"Lever"},
{"id":"70", "name":"Stone Pressure Plate"},
{"id":"71", "name":"Iron Door Block"},
{"id":"72", "name":"Wooden Pressure Plate"},
{"id":"73", "name":"Redstone Ore"},
{"id":"74", "name":"Glowing Redstone Ore"},
{"id":"75", "name":"Redstone Torch (off)"},
{"id":"76", "name":"Redstone Torch (on)"},
{"id":"77", "name":"Stone Button"},
{"id":"78", "name":"Snow"},
{"id":"79", "name":"Ice"},
{"id":"80", "name":"Snow Block"},
{"id":"81", "name":"Cactus"},
{"id":"82", "name":"Clay"},
{"id":"83", "name":"Sugar Cane"},
{"id":"84", "name":"Jukebox"},
{"id":"85", "name":"Fence"},
{"id":"86", "name":"Pumpkin"},
{"id":"87", "name":"Netherrack"},
{"id":"88", "name":"Soul Sand"},
{"id":"89", "name":"Glowstone"},
{"id":"90", "name":"Portal"},
{"id":"91", "name":"Jack-O-Lantern"},
{"id":"92", "name":"Cake Block"},
{"id":"93", "name":"Redstone Repeater Block (off)"},
{"id":"94", "name":"Redstone Repeater Block (on)"},
{"id":"95", "name":"Locked Chest"},
{"id":"96", "name":"Trapdoor"},
{"id":"97", "name":"Stone (Silverfish)"},
{"id":"97:1", "name":"Cobblestone (Silverfish)"},
{"id":"97:2", "name":"Stone Brick (Silverfish)"},
{"id":"98", "name":"Stone Brick"},
{"id":"98:1", "name":"Mossy Stone Brick"},
{"id":"98:2", "name":"Cracked Stone Brick"},
{"id":"98:3", "name":"Chiseled Stone Brick"},
{"id":"99", "name":"Red Mushroom Cap"},
{"id":"100", "name":"Brown Mushroom Cap"},
{"id":"101", "name":"Iron Bars"},
{"id":"102", "name":"Glass Pane"},
{"id":"103", "name":"Melon Block"},
{"id":"104", "name":"Pumpkin Stem"},
{"id":"105", "name":"Melon Stem"},
{"id":"106", "name":"Vines"},
{"id":"107", "name":"Fence Gate"},
{"id":"108", "name":"Brick Stairs"},
{"id":"109", "name":"Stone Brick Stairs"},
{"id":"110", "name":"Mycelium"},
{"id":"111", "name":"Lily Pad"},
{"id":"112", "name":"Nether Brick"},
{"id":"113", "name":"Nether Brick Fence"},
{"id":"114", "name":"Nether Brick Stairs"},
{"id":"115", "name":"Nether Wart"},
{"id":"116", "name":"Enchantment Table"},
{"id":"117", "name":"Brewing Stand"},
{"id":"118", "name":"Cauldron"},
{"id":"119", "name":"End Portal"},
{"id":"120", "name":"End Portal Frame"},
{"id":"121", "name":"End Stone"},
{"id":"122", "name":"Dragon Egg"},
{"id":"123", "name":"Redstone Lamp (inactive)"},
{"id":"124", "name":"Redstone Lamp (active)"},
{"id":"125", "name":"Double Oak Wood Slab"},
{"id":"125:1", "name":"Double Spruce Wood Slab"},
{"id":"125:2", "name":"Double Birch Wood Slab"},
{"id":"125:3", "name":"Double Jungle Wood Slab"},
{"id":"126", "name":"Oak Wood Slab"},
{"id":"126:1", "name":"Spruce Wood Slab"},
{"id":"126:2", "name":"Birch Wood Slab"},
{"id":"126:3", "name":"Jungle Wood Slab"},
{"id":"127", "name":"Cocoa Plant"},
{"id":"128", "name":"Sandstone Stairs"},
{"id":"129", "name":"Emerald Ore"},
{"id":"130", "name":"Ender Chest"},
{"id":"131", "name":"Tripwire Hook"},
{"id":"132", "name":"Tripwire"},
{"id":"133", "name":"Emerald Block"},
{"id":"134", "name":"Spruce Wood Stairs"},
{"id":"135", "name":"Birch Wood Stairs"},
{"id":"136", "name":"Jungle Wood Stairs"},
{"id":"137", "name":"Command Block"},
{"id":"138", "name":"Beacon Block"},
{"id":"139", "name":"Cobblestone Wall"},
{"id":"139:1", "name":"Mossy Cobblestone Wall"},
{"id":"140", "name":"Flower Pot"},
{"id":"141", "name":"Carrots"},
{"id":"142", "name":"Potatoes"},
{"id":"143", "name":"Wooden Button"},
{"id":"144", "name":"Mob Head"},
{"id":"145", "name":"Anvil"},
{"id":"146", "name":"Trapped Chest"},
{"id":"147", "name":"Weighted Pressure Plate (light)"},
{"id":"148", "name":"Weighted Pressure Plate (heavy)"},
{"id":"149", "name":"Redstone Comparator (inactive)"},
{"id":"150", "name":"Redstone Comparator (active)"},
{"id":"151", "name":"Daylight Sensor"},
{"id":"152", "name":"Redstone Block"},
{"id":"153", "name":"Nether Quartz Ore"},
{"id":"154", "name":"Hopper"},
{"id":"155", "name":"Quartz Block"},
{"id":"155:1", "name":"Chiseled Quartz Block"},
{"id":"155:2", "name":"Pillar Quartz Block"},
{"id":"156", "name":"Quartz Stairs"},
{"id":"157", "name":"Activator Rail"},
{"id":"158", "name":"Dropper"},
{"id":"256", "name":"Iron Shovel"},
{"id":"257", "name":"Iron Pickaxe"},
{"id":"258", "name":"Iron Axe"},
{"id":"259", "name":"Flint and Steel"},
{"id":"260", "name":"Apple"},
{"id":"261", "name":"Bow"},
{"id":"262", "name":"Arrow"},
{"id":"263", "name":"Coal"},
{"id":"263:1", "name":"Charcoal"},
{"id":"264", "name":"Diamond"},
{"id":"265", "name":"Iron Ingot"},
{"id":"266", "name":"Gold Ingot"},
{"id":"267", "name":"Iron Sword"},
{"id":"268", "name":"Wooden Sword"},
{"id":"269", "name":"Wooden Shovel"},
{"id":"270", "name":"Wooden Pickaxe"},
{"id":"271", "name":"Wooden Axe"},
{"id":"272", "name":"Stone Sword"},
{"id":"273", "name":"Stone Shovel"},
{"id":"274", "name":"Stone Pickaxe"},
{"id":"275", "name":"Stone Axe"},
{"id":"276", "name":"Diamond Sword"},
{"id":"277", "name":"Diamond Shovel"},
{"id":"278", "name":"Diamond Pickaxe"},
{"id":"279", "name":"Diamond Axe"},
{"id":"280", "name":"Stick"},
{"id":"281", "name":"Bowl"},
{"id":"282", "name":"Mushroom Soup"},
{"id":"283", "name":"Gold Sword"},
{"id":"284", "name":"Gold Shovel"},
{"id":"285", "name":"Gold Pickaxe"},
{"id":"286", "name":"Gold Axe"},
{"id":"287", "name":"String"},
{"id":"288", "name":"Feather"},
{"id":"289", "name":"Sulphur"},
{"id":"290", "name":"Wooden Hoe"},
{"id":"291", "name":"Stone Hoe"},
{"id":"292", "name":"Iron Hoe"},
{"id":"293", "name":"Diamond Hoe"},
{"id":"294", "name":"Gold Hoe"},
{"id":"295", "name":"Wheat Seeds"},
{"id":"296", "name":"Wheat"},
{"id":"297", "name":"Bread"},
{"id":"298", "name":"Leather Helmet"},
{"id":"299", "name":"Leather Chestplate"},
{"id":"300", "name":"Leather Leggings"},
{"id":"301", "name":"Leather Boots"},
{"id":"302", "name":"Chainmail Helmet"},
{"id":"303", "name":"Chainmail Chestplate"},
{"id":"304", "name":"Chainmail Leggings"},
{"id":"305", "name":"Chainmail Boots"},
{"id":"306", "name":"Iron Helmet"},
{"id":"307", "name":"Iron Chestplate"},
{"id":"308", "name":"Iron Leggings"},
{"id":"309", "name":"Iron Boots"},
{"id":"310", "name":"Diamond Helmet"},
{"id":"311", "name":"Diamond Chestplate"},
{"id":"312", "name":"Diamond Leggings"},
{"id":"313", "name":"Diamond Boots"},
{"id":"314", "name":"Gold Helmet"},
{"id":"315", "name":"Gold Chestplate"},
{"id":"316", "name":"Gold Leggings"},
{"id":"317", "name":"Gold Boots"},
{"id":"318", "name":"Flint"},
{"id":"319", "name":"Raw Porkchop"},
{"id":"320", "name":"Cooked Porkchop"},
{"id":"321", "name":"Painting"},
{"id":"322", "name":"Golden Apple"},
{"id":"322:1", "name":"Enchanted Golden Apple"},
{"id":"323", "name":"Sign"},
{"id":"324", "name":"Wooden Door"},
{"id":"325", "name":"Bucket"},
{"id":"326", "name":"Water Bucket"},
{"id":"327", "name":"Lava Bucket"},
{"id":"328", "name":"Minecart"},
{"id":"329", "name":"Saddle"},
{"id":"330", "name":"Iron Door"},
{"id":"331", "name":"Redstone"},
{"id":"332", "name":"Snowball"},
{"id":"333", "name":"Boat"},
{"id":"334", "name":"Leather"},
{"id":"335", "name":"Milk Bucket"},
{"id":"336", "name":"Clay Brick"},
{"id":"337", "name":"Clay Balls"},
{"id":"338", "name":"Sugarcane"},
{"id":"339", "name":"Paper"},
{"id":"340", "name":"Book"},
{"id":"341", "name":"Slimeball"},
{"id":"342", "name":"Storage Minecart"},
{"id":"343", "name":"Powered Minecart"},
{"id":"344", "name":"Egg"},
{"id":"345", "name":"Compass"},
{"id":"346", "name":"Fishing Rod"},
{"id":"347", "name":"Clock"},
{"id":"348", "name":"Glowstone Dust"},
{"id":"349", "name":"Raw Fish"},
{"id":"350", "name":"Cooked Fish"},
{"id":"351", "name":"Ink Sack"},
{"id":"351:1", "name":"Rose Red"},
{"id":"351:2", "name":"Cactus Green"},
{"id":"351:3", "name":"Coco Beans"},
{"id":"351:4", "name":"Lapis Lazuli"},
{"id":"351:5", "name":"Purple Dye"},
{"id":"351:6", "name":"Cyan Dye"},
{"id":"351:7", "name":"Light Gray Dye"},
{"id":"351:8", "name":"Gray Dye"},
{"id":"351:9", "name":"Pink Dye"},
{"id":"351:10", "name":"Lime Dye"},
{"id":"351:11", "name":"Dandelion Yellow"},
{"id":"351:12", "name":"Light Blue Dye"},
{"id":"351:13", "name":"Magenta Dye"},
{"id":"351:14", "name":"Orange Dye"},
{"id":"351:15", "name":"Bone Meal"},
{"id":"352", "name":"Bone"},
{"id":"353", "name":"Sugar"},
{"id":"354", "name":"Cake"},
{"id":"355", "name":"Bed"},
{"id":"356", "name":"Redstone Repeater"},
{"id":"357", "name":"Cookie"},
{"id":"358", "name":"Map"},
{"id":"359", "name":"Shears"},
{"id":"360", "name":"Melon"},
{"id":"361", "name":"Pumpkin Seeds"},
{"id":"362", "name":"Melon Seeds"},
{"id":"363", "name":"Raw Beef"},
{"id":"364", "name":"Steak"},
{"id":"365", "name":"Raw Chicken"},
{"id":"366", "name":"Cooked Chicken"},
{"id":"367", "name":"Rotten Flesh"},
{"id":"368", "name":"Ender Pearl"},
{"id":"369", "name":"Blaze Rod"},
{"id":"370", "name":"Ghast Tear"},
{"id":"371", "name":"Gold Nugget"},
{"id":"372", "name":"Nether Wart Seeds"},
{"id":"373", "name":"Potion"},
{"id":"374", "name":"Glass Bottle"},
{"id":"375", "name":"Spider Eye"},
{"id":"376", "name":"Fermented Spider Eye"},
{"id":"377", "name":"Blaze Powder"},
{"id":"378", "name":"Magma Cream"},
{"id":"379", "name":"Brewing Stand"},
{"id":"380", "name":"Cauldron"},
{"id":"381", "name":"Eye of Ender"},
{"id":"382", "name":"Glistering Melon"},
{"id":"383:50", "name":"Spawn Creeper"},
{"id":"383:51", "name":"Spawn Skeleton"},
{"id":"383:52", "name":"Spawn Spider"},
{"id":"383:54", "name":"Spawn Zombie"},
{"id":"383:55", "name":"Spawn Slime"},
{"id":"383:56", "name":"Spawn Ghast"},
{"id":"383:57", "name":"Spawn Pigman"},
{"id":"383:58", "name":"Spawn Enderman"},
{"id":"383:59", "name":"Spawn Cave Spider"},
{"id":"383:60", "name":"Spawn Silverfish"},
{"id":"383:61", "name":"Spawn Blaze"},
{"id":"383:62", "name":"Spawn Magma Cube"},
{"id":"383:65", "name":"Spawn Bat"},
{"id":"383:66", "name":"Spawn Witch"},
{"id":"383:90", "name":"Spawn Pig"},
{"id":"383:91", "name":"Spawn Sheep"},
{"id":"383:92", "name":"Spawn Cow"},
{"id":"383:93", "name":"Spawn Chicken"},
{"id":"383:94", "name":"Spawn Squid"},
{"id":"383:95", "name":"Spawn Wolf"},
{"id":"383:96", "name":"Spawn Mooshroom"},
{"id":"383:98", "name":"Spawn Ocelot"},
{"id":"383:120", "name":"Spawn Villager"},
{"id":"384", "name":"Bottle o' Enchanting"},
{"id":"385", "name":"Fire Charge"},
{"id":"386", "name":"Book and Quill"},
{"id":"387", "name":"Written Book"},
{"id":"388", "name":"Emerald"},
{"id":"389", "name":"Item Frame"},
{"id":"390", "name":"Flower Pot"},
{"id":"391", "name":"Carrots"},
{"id":"392", "name":"Potato"},
{"id":"393", "name":"Baked Potato"},
{"id":"394", "name":"Poisonous Potato"},
{"id":"395", "name":"Map"},
{"id":"396", "name":"Golden Carrot"},
{"id":"397", "name":"Mob Head (Skeleton)"},
{"id":"397:1", "name":"Mob Head (Wither Skeleton)"},
{"id":"397:2", "name":"Mob Head (Zombie)"},
{"id":"397:3", "name":"Mob Head (Human)"},
{"id":"397:4", "name":"Mob Head (Creeper)"},
{"id":"398", "name":"Carrot on a Stick"},
{"id":"399", "name":"Nether Star"},
{"id":"400", "name":"Pumpkin Pie"},
{"id":"401", "name":"Firework Rocket"},
{"id":"402", "name":"Firework Star"},
{"id":"403", "name":"Enchanted Book"},
{"id":"404", "name":"Redstone Comparator"},
{"id":"405", "name":"Nether Brick"},
{"id":"406", "name":"Nether Quartz"},
{"id":"407", "name":"Minecart with TNT"},
{"id":"408", "name":"Minecart with Hopper"},
{"id":"2256", "name":"13 Disc"},
{"id":"2257", "name":"Cat Disc"},
{"id":"2258", "name":"Blocks Disc"},
{"id":"2259", "name":"Chirp Disc"},
{"id":"2260", "name":"Far Disc"},
{"id":"2261", "name":"Mall Disc"},
{"id":"2262", "name":"Mellohi Disc"},
{"id":"2263", "name":"Stal Disc"},
{"id":"2264", "name":"Strad Disc"},
{"id":"2265", "name":"Ward Disc"},
{"id":"2266", "name":"11 Disc"},
{"id":"2267", "name":"Wait Disc"}];

function setBlockRefs() {
var splitIDTest = /\:/;
console.log("mapping " + blockIDs.length + " items in blockIDs");
	for (i=0;i<blockIDs.length;i++) {
		var blockID = blockIDs[i]['id'];
		if (splitIDTest.test(blockID)) {
			blockID = blockID.replace(':', '-');
		} else {
			blockID += "-0";
		}
		console.log("blockID=" + blockID);
		blocksByID[blockID] = blockIDs[i];
	}
}

setBlockRefs();

